command_homepage:
    pattern:  /
    defaults: { _controller: DevBieresCommandBundle:Default:index }

list:
    pattern: /command/list
    defaults: { _controller: DevBieresCommandBundle:Command:List }

clear_cache:
    pattern: /command/clearcache
    defaults: { _controller: DevBieresCommandBundle:Command:ClearCache }

router_debug:
    pattern: /command/router/debug
    defaults: { _controller: DevBieresCommandBundle:Command:RouterDebug }


doctrine_schema_create:
    pattern: /command/doctrine/schema/create
    defaults: { _controller: DevBieresCommandBundle:DoctrineCommand:DoctrineSchemaCreate }

doctrine_schema_update:
    pattern: /command/doctrine/schema/update
    defaults: { _controller: DevBieresCommandBundle:DoctrineCommand:DoctrineSchemaUpdate }

doctrine_schema_validate:
    pattern: /command/doctrine/schema/validate
    defaults: { _controller: DevBieresCommandBundle:DoctrineCommand:DoctrineSchemaValidate }

doctrine_schema_drop:
    pattern: /command/doctrine/schema/drop
    defaults: { _controller: DevBieresCommandBundle:DoctrineCommand:DoctrineSchemaDrop }


assets_install:
    pattern: /command/assets/install
    defaults: { _controller: DevBieresCommandBundle:Command:AssetsInstall }

generate_bundle:
    pattern: /command/generate/bundle
    defaults: { _controller: DevBieresCommandBundle:GenerateCommand:GenerateBundle }

generic:
    pattern: /generic
    defaults: { _controller: DevBieresCommandBundle:Command:Generic }

