parameters:
#    dev_bieres_command.example.class: DevBieres\CommandBundle\Example

services:
#    dev_bieres_command.example:
#        class: %dev_bieres_command.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
