parameters:
#    dev_bieres_command.example.class: DevBieres\CommandBundle\Example

services:
   devbieres.command.type.bundle:
     class: DevBieres\CommandBundle\Form\Type\BundleChoiceType
     arguments:
       - "@service_container"
     tags:
       - { name: form.type, alias: bundle }
   devbieres.command.type.format:
     class: DevBieres\CommandBundle\Form\Type\FormatChoiceType
     tags:
       - { name: form.type, alias: formatchoice }
   devbieres.command.type.fieldtype:
     class: DevBieres\CommandBundle\Form\Type\FieldTypeChoiceType
     tags:
      - { name: form.type, alias: fieldtypechoice }


